# Generated by Django 5.0.2 on 2024-07-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(default=None, max_length=250, null=True, upload_to='product/')),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.TextField()),
            ],
        ),
    ]
