# Generated by Django 5.0.2 on 2024-07-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=50)),
                ('passout', models.CharField(max_length=5)),
                ('experience', models.CharField(max_length=5)),
                ('summary', models.TextField()),
                ('resume', models.FileField(default=None, max_length=1000, null=True, upload_to='resume/')),
            ],
        ),
    ]
