# Generated by Django 5.0.2 on 2024-07-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='resume',
            field=models.FileField(default=None, null=True, upload_to='resume/'),
        ),
    ]
