# Generated by Django 5.0.2 on 2024-07-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.FileField(default=None, max_length=250, null=True, upload_to='service/')),
                ('service_name', models.CharField(max_length=50)),
                ('service_desc', models.TextField()),
            ],
        ),
    ]
