# Generated by Django 5.0.2 on 2024-07-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_image', models.FileField(default=None, max_length=250, null=True, upload_to='internship/')),
                ('internship_name', models.CharField(max_length=20)),
                ('internship_desc', models.TextField()),
            ],
        ),
    ]
