# Generated by Django 5.0.2 on 2024-07-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='internship_name',
            field=models.CharField(max_length=100),
        ),
    ]
