# Generated by Django 5.0.2 on 2024-07-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_alter_internship_internship_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='internship_desc',
            new_name='job_desc',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='internship_image',
            new_name='job_image',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='internship_name',
            new_name='job_name',
        ),
    ]
